#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Validate that every skill declares a valid scope, and keep AGENTS.md honest.

Skills are FLAT under `skills/` (open Agent-Skills standard — multi-tool
discovery via .claude/skills, .agents/skills, .github/skills). Because they
can't be foldered by tier, their tier lives in the SKILL.md frontmatter as
`metadata.scope` (or legacy top-level `scope:`). This validator is the
enforcement that makes that frontmatter load-bearing instead of drift-prone.

What it does:
  1. Every `skills/*/SKILL.md` must declare scope ∈ {core, org, user}.
     Missing / invalid → exit 1 (CI + pre-commit gate).
  2. Keeps the auto-generated SKILL-SCOPE block in AGENTS.md in sync with
     reality. `--write` regenerates it; default mode fails if it drifted.

Usage:
  validate-skill-scope.py            # validate scopes + check AGENTS.md block
  validate-skill-scope.py --write    # regenerate the AGENTS.md block in place
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("validate-skill-scope: PyYAML required (pip install pyyaml)")

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
AGENTS = REPO / "AGENTS.md"

VALID = ("core", "org", "personal", "user")
SHIPS_TO = {
    "core": "open-bridge + your org overlay + local",
    "org": "your org overlay + local",
    "personal": "your personal overlay + local",
    "user": "local only",
}
START = "<!-- SKILL-SCOPE:START (auto-generated by scripts/validate-skill-scope.py — do not edit by hand) -->"
END = "<!-- SKILL-SCOPE:END -->"


def frontmatter(path: Path) -> dict | None:
    """Return the parsed YAML frontmatter of a markdown file, or None."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        data = yaml.safe_load(parts[1])
        return data if isinstance(data, dict) else None
    except yaml.YAMLError:
        return None


def scope_of(fm: dict | None) -> str | None:
    if not fm:
        return None
    meta = fm.get("metadata")
    if isinstance(meta, dict) and meta.get("scope"):
        return str(meta["scope"]).strip()
    if fm.get("scope"):
        return str(fm["scope"]).strip()
    return None


def collect() -> tuple[dict[str, list[str]], list[str]]:
    """Return ({scope: [skill names]}, [error strings])."""
    by_scope: dict[str, list[str]] = {s: [] for s in VALID}
    errors: list[str] = []
    # Iterate DIRECTORIES, not `*/SKILL.md`. Globbing the file made a skill
    # directory WITHOUT a SKILL.md invisible: it was neither counted nor flagged,
    # so the validator printed "92 skills valid" against 93 directories. The
    # missing one declared no tier at all, and every file in it fell through the
    # router's frontmatter read — the exact drift this gate exists to catch.
    for skill_dir in sorted(d for d in SKILLS_DIR.iterdir()
                            if d.is_dir() and not d.name.startswith("_")):
        name = skill_dir.name
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            errors.append(
                f"{name}: directory has no SKILL.md — it declares no tier, so the "
                f"scope router cannot classify anything inside it"
            )
            continue
        sc = scope_of(frontmatter(skill_md))
        if sc is None:
            errors.append(f"{name}: no scope declared (need metadata.scope ∈ {VALID})")
        elif sc not in VALID:
            errors.append(f"{name}: invalid scope '{sc}' (must be one of {VALID})")
        else:
            by_scope[sc].append(name)
    return by_scope, errors


def render_block(by_scope: dict[str, list[str]]) -> str:
    lines = [
        START,
        "",
        "| Scope | Ships to | Skills |",
        "|-------|----------|--------|",
    ]
    for sc in VALID:
        names = ", ".join(f"`{n}`" for n in sorted(by_scope[sc])) or "—"
        lines.append(f"| `{sc}` | {SHIPS_TO[sc]} | {names} |")
    lines += ["", END]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END) :]
        return pre + block + post
    raise SystemExit(
        f"validate-skill-scope: markers {START!r} / {END!r} not found in AGENTS.md — "
        "add them once where the skill-scope table should live."
    )


def main() -> int:
    write = "--write" in sys.argv[1:]
    by_scope, errors = collect()

    if errors:
        print("✗ skill-scope validation failed:", file=sys.stderr)
        for e in errors:
            print(f"   - {e}", file=sys.stderr)
        return 1

    total = sum(len(v) for v in by_scope.values())
    block = render_block(by_scope)
    current = AGENTS.read_text(encoding="utf-8")

    if write:
        AGENTS.write_text(splice(current, block), encoding="utf-8")
        print(f"✓ {total} skills valid · AGENTS.md SKILL-SCOPE block regenerated "
              f"({' · '.join(f'{k}:{len(v)}' for k, v in by_scope.items())})")
        return 0

    # check mode
    if START not in current or block not in current:
        print("✗ AGENTS.md SKILL-SCOPE block is drifted or missing.", file=sys.stderr)
        print("   Run: python3 scripts/validate-skill-scope.py --write", file=sys.stderr)
        return 1

    print(f"✓ {total} skills valid · AGENTS.md in sync "
          f"({' · '.join(f'{k}:{len(v)}' for k, v in by_scope.items())})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
