#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Validate that every skill declares a valid scope, and keep AGENTS.md honest.

Skills are FLAT under `skills/` (open Agent-Skills standard — multi-tool
discovery via .claude/skills, .agents/skills, .github/skills). Because they
can't be foldered by tier, their tier lives in the SKILL.md frontmatter as
`metadata.scope` (or legacy top-level `scope:`). This validator is the
enforcement that makes that frontmatter load-bearing instead of drift-prone.

What it does:
  1. Every `skills/*/SKILL.md` must declare scope ∈ {core, org, user, personal}.
     Missing / invalid → exit 1 (CI + pre-commit gate). This is the load-bearing
     part: it makes the frontmatter authoritative instead of drift-prone.
  2. Refreshes the per-instance tier map at `.bridge/skill-scope.md`.

Why the map is NOT in AGENTS.md any more (changed 2026-08-19):
  Every instance has a different skill tree by design (org skills, personal
  skills, local-only skills). A table generated from the LOCAL tree and embedded
  in a CORE file can therefore never converge with upstream: it conflicted on
  every `git merge <oss-core>/main`, and promoting it would have carried local
  org/customer skill names into the public OSS repo. The map is derived data, so
  it now lives beside the other derived state under `.bridge/` (gitignored, and
  already classified local-only by scripts/categorize-commits.py). AGENTS.md
  keeps a static description of the tiers and points here. The authoritative
  tier was always the frontmatter, never the table.

Usage:
  validate-skill-scope.py            # validate scopes + refresh the map
  validate-skill-scope.py --check    # validate only, write nothing
  validate-skill-scope.py --write    # accepted, same as default (back-compat)
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("validate-skill-scope: PyYAML required (pip install pyyaml)")

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
# Derived, per-instance, never committed: .bridge/ is gitignored AND matched by
# the `^\.bridge/` USER pattern in scripts/categorize-commits.py, so this file
# needs no new router literal to stay local-only.
SCOPE_MAP = REPO / ".bridge" / "skill-scope.md"

VALID = ("core", "org", "personal", "user")
SHIPS_TO = {
    "core": "open-bridge + your org overlay + local",
    "org": "your org overlay + local",
    "personal": "your personal overlay + local",
    "user": "local only",
}
def frontmatter(path: Path) -> dict | None:
    """Return the parsed YAML frontmatter of a markdown file, or None."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None
    try:
        data = yaml.safe_load(parts[1])
        return data if isinstance(data, dict) else None
    except yaml.YAMLError:
        return None


def scope_of(fm: dict | None) -> str | None:
    if not fm:
        return None
    meta = fm.get("metadata")
    if isinstance(meta, dict) and meta.get("scope"):
        return str(meta["scope"]).strip()
    if fm.get("scope"):
        return str(fm["scope"]).strip()
    return None


def collect() -> tuple[dict[str, list[str]], list[str]]:
    """Return ({scope: [skill names]}, [error strings])."""
    by_scope: dict[str, list[str]] = {s: [] for s in VALID}
    errors: list[str] = []
    # Iterate DIRECTORIES, not `*/SKILL.md`. Globbing the file made a skill
    # directory WITHOUT a SKILL.md invisible: it was neither counted nor flagged,
    # so the validator printed "92 skills valid" against 93 directories. The
    # missing one declared no tier at all, and every file in it fell through the
    # router's frontmatter read — the exact drift this gate exists to catch.
    for skill_dir in sorted(d for d in SKILLS_DIR.iterdir()
                            if d.is_dir() and not d.name.startswith("_")):
        name = skill_dir.name
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            errors.append(
                f"{name}: directory has no SKILL.md — it declares no tier, so the "
                f"scope router cannot classify anything inside it"
            )
            continue
        sc = scope_of(frontmatter(skill_md))
        if sc is None:
            errors.append(f"{name}: no scope declared (need metadata.scope ∈ {VALID})")
        elif sc not in VALID:
            errors.append(f"{name}: invalid scope '{sc}' (must be one of {VALID})")
        else:
            by_scope[sc].append(name)
    return by_scope, errors


def render_map(by_scope: dict[str, list[str]]) -> str:
    """The per-instance tier map. Derived from frontmatter, never authoritative."""
    lines = [
        "<!-- GENERATED by scripts/validate-skill-scope.py — do not edit by hand.",
        "     Per-instance and gitignored: your skill tree is not anyone else's.",
        "     The authoritative tier is `metadata.scope` in each skills/*/SKILL.md. -->",
        "",
        "# Skill tier map",
        "",
        "| Scope | Ships to | Skills |",
        "|-------|----------|--------|",
    ]
    for sc in VALID:
        names = ", ".join(f"`{n}`" for n in sorted(by_scope[sc])) or "—"
        lines.append(f"| `{sc}` | {SHIPS_TO[sc]} | {names} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    argv = sys.argv[1:]
    check_only = "--check" in argv
    by_scope, errors = collect()

    # Job 1 — the gate. A bad or missing scope fails regardless of mode.
    if errors:
        print("✗ skill-scope validation failed:", file=sys.stderr)
        for e in errors:
            print(f"   - {e}", file=sys.stderr)
        return 1

    total = sum(len(v) for v in by_scope.values())
    tally = " · ".join(f"{k}:{len(v)}" for k, v in by_scope.items())

    # Job 2 — refresh the derived map. It is gitignored and per-instance, so
    # there is no "drifted" failure mode to report: it is simply rewritten.
    if check_only:
        print(f"✓ {total} skills valid ({tally}) · map not written (--check)")
        return 0

    SCOPE_MAP.parent.mkdir(parents=True, exist_ok=True)
    SCOPE_MAP.write_text(render_map(by_scope), encoding="utf-8")
    rel = SCOPE_MAP.relative_to(REPO)
    print(f"✓ {total} skills valid ({tally}) · map refreshed at {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
